### PR TITLE
Submission for the EU slot

### PR DESCRIPTION
**Pull request by hmemcpy**
Please review and see if the info is filled out correctly.

### CODE REVIEW

**Comment by danielmarbach** [comment]
@hmemcpy :+1: Looks good and definitely an interesting contribution. Let's see what others think

**Comment by colin-higgins** [comment]
:+1:

**Comment by blairconrad** [comment]
:+1:

**Comment by dchirutac** [comment]
:+1:

**Comment by dotnetricardo** [comment]
:+1:

**Comment by jsonmez** [comment]
:+1:

**Comment by hmemcpy** [comment]
So is this good to go, then?

**Comment by danielmarbach** [comment]
The initial idea was to merge 1 week before the slot. But if nobody disagrees here I'm OK with merging it earlier since nobody else has taken it yet.

**Comment by blairconrad** [comment]
:+1:

**Comment by khellang** [comment]
:heart: this! :shipit:

**Pull request merged**
