### PR TITLE
Submission for new slot and proposed session

### PR DESCRIPTION
**Pull request by darrelmiller**
This is a proposal for a session by Glenn Block and myself that will be a HTTP Q&A.

### CODE REVIEW

**Comment by danielmarbach** [comment]
Great stuff :+1: @darrelmiller Can you provide 1-2 tags?

**Comment by danielmarbach** [comment]
Btw. @darrelmiller this PR is also a great test for my layout. I didn't think about brown-bags hosted by multiple people.

**Comment by darrelmiller** [comment]
I tried adding HTTP and API as tags in my local copy but Jekyll kept choking on the page saying there was an unknown key.  Are there specific well known tags?

**Comment by danielmarbach** [comment]
Paste them here and I'll fix it

**Comment by darrelmiller** [comment]
I just tried:
    tags: HTTP, API

**Pull request merged**
